spring:
  application:
    name: customerChurn

  datasource:
    url: jdbc:postgresql://localhost:5432/customer_churn
    username: postgres
    password: root

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

kind: Application